apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: intelligent-healing
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'build-worker'
        metrics_path: /metrics
        static_configs:
          - targets: ['build-worker:8000']

      - job_name: 'pipeline-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['pipeline-service:8000']

      - job_name: 'api-gateway'
        metrics_path: /metrics
        static_configs:
          - targets: ['api-gateway:8000']
